[package]
name = "raylib_ttf_alias_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
raylib = "3.7.0"
regex = "1.7.1"
structopt = "0.3.26"
